version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: vietlott_db
    restart: always
    environment:
      POSTGRES_USER: vietlott_user
      POSTGRES_PASSWORD: vietlott_password
      POSTGRES_DB: vietlott_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: